import {useEffect,useRef,useState,forwardRef,useImperativeHandle} from 'react';
import Head from 'next/head';

const Player=forwardRef(function Player({onStatus},ref){
 const canvas=useRef(null),worker=useRef(null);const [playing,setPlaying]=useState(false);
 useEffect(()=>{const w=new Worker(new URL('../workers/player.worker.js',import.meta.url));worker.current=w;w.onmessage=e=>{if(e.data.type==='status')onStatus(e.data.text);if(e.data.type==='playing')setPlaying(e.data.value);if(e.data.type==='error')onStatus('Player error: '+e.data.message)};const c=canvas.current;if(c?.transferControlToOffscreen){const off=c.transferControlToOffscreen();w.postMessage({type:'init',canvas:off},[off])}else onStatus('OffscreenCanvas is unavailable in this browser.');return()=>w.terminate()},[onStatus]);
 useImperativeHandle(ref,()=>({async load(id){const r=await fetch('/api/playback/session?videoId='+encodeURIComponent(id));const d=await r.json();if(!r.ok)return onStatus(d.error);wPost({type:'open',url:d.streamUrl})}}));
 const wPost=m=>worker.current?.postMessage(m);
 return <div className="player"><canvas ref={canvas}/><div className="controls"><button onClick={()=>wPost({type:playing?'pause':'resume'})}>{playing?'❚❚':'▶'}</button><button onClick={()=>wPost({type:'seek',seconds:-10})}>↶10</button><button onClick={()=>wPost({type:'seek',seconds:10})}>10↷</button></div></div>
});
export default function Home(){const[q,setQ]=useState(''),[items,setItems]=useState([]),[status,setStatus]=useState('Ready'),player=useRef(null);async function search(e){e.preventDefault();if(!q.trim())return;setStatus('Searching…');const r=await fetch('/api/youtube/search?query='+encodeURIComponent(q));const d=await r.json();setItems(d.items||[]);setStatus(d.error||`${(d.items||[]).length} results`) }function demo(){setStatus("Loading local MPEG-TS demo…");player.current?.load("demo")}function choose(v){setStatus('YouTube search is metadata-only until an authorized media provider is connected.');player.current?.load(v.id.videoId)}return <><Head><title>CanvasTube</title><meta name="viewport" content="width=device-width,initial-scale=1"/></Head><main><header><b>CanvasTube</b><span>custom canvas media prototype</span></header><Player ref={player} onStatus={setStatus}/><div style={{padding:"12px 0"}}><button onClick={demo} style={{padding:"12px 20px",background:"#e82127",color:"white",border:0,borderRadius:8,cursor:"pointer"}}>▶ Play local demo (no API key)</button></div><form onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search YouTube"/><button>Search</button></form><div className="status">{status}</div><section>{items.map(v=><button className="result" key={v.id.videoId} onClick={()=>choose(v)}><img src={v.snippet.thumbnails.medium.url}/><span><strong>{v.snippet.title}</strong><small>{v.snippet.channelTitle}</small></span></button>)}</section></main></>}
