// Original, minimal MPEG-TS -> H.264 Annex B -> WebCodecs -> OffscreenCanvas demo.
// Intentionally video-only. PAT/PMT, PES, frame boundaries and production A/V sync
// need hardening before this is used with arbitrary live streams.
let ctx, decoder, playing = true, stopped = false, videoPid = -1;
let packetBytes = new Uint8Array(0), pesParts = [], pesLength = 0;
let frames = [], lastPts = 0, clockStart = 0, firstPts = null, rendering = false;
const emit = (type, extra = {}) => postMessage({ type, ...extra });
const concat = (a,b) => {const o=new Uint8Array(a.length+b.length);o.set(a);o.set(b,a.length);return o};
const join = parts => {let n=parts.reduce((s,p)=>s+p.length,0),o=new Uint8Array(n),i=0;for(const p of parts){o.set(p,i);i+=p.length}return o};
const pts = p => ((p[0]&14)*536870912)+(p[1]<<22)+((p[2]&254)<<14)+(p[3]<<7)+(p[4]>>1);
function parsePAT(p){let i=1+p[0];if(i+8>=p.length||p[i]!==0)return -1;let end=i+3+(((p[i+1]&15)<<8)|p[i+2])-4;i+=8;while(i+4<=end){let prog=(p[i]<<8)|p[i+1],pid=((p[i+2]&31)<<8)|p[i+3];if(prog)return pid;i+=4}return -1}
let pmtPid=-1;
function parsePMT(p){let i=1+p[0];if(i+12>=p.length||p[i]!==2)return;let end=i+3+(((p[i+1]&15)<<8)|p[i+2])-4;let info=((p[i+10]&15)<<8)|p[i+11];i+=12+info;while(i+5<=end){let type=p[i],pid=((p[i+1]&31)<<8)|p[i+2],len=((p[i+3]&15)<<8)|p[i+4];if(type===0x1b){videoPid=pid;emit('status',{text:'H.264 video PID: '+pid});return}i+=5+len}}
function nalUnits(bytes){let starts=[];for(let i=0;i+3<bytes.length;i++){if(bytes[i]===0&&bytes[i+1]===0&&(bytes[i+2]===1||(bytes[i+2]===0&&bytes[i+3]===1))){starts.push(i);i+=bytes[i+2]===1?2:3}}return starts.map((s,j)=>bytes.subarray(s,starts[j+1]??bytes.length))}
function flushPES(){if(!pesParts.length||!decoder)return;let b=join(pesParts);pesParts=[];pesLength=0;if(b.length<14||b[0]!==0||b[1]!==0||b[2]!==1)return;let header=9+b[8],t=(b[7]&0x80)?pts(b.subarray(9,14))/90:lastPts+41667;lastPts=t;let payload=b.subarray(header);let nals=nalUnits(payload),key=nals.some(n=>{let k=n[2]===1?3:4;return (n[k]&31)===5});if(!nals.length)return;try{decoder.decode(new EncodedVideoChunk({type:key?'key':'delta',timestamp:Math.round(t),data:payload}))}catch(e){emit('error',{message:'Decode failed: '+e.message})}}
function parseTS(bytes){packetBytes=concat(packetBytes,bytes);let off=0;while(off+188<=packetBytes.length){if(packetBytes[off]!==0x47){off++;continue}let p=packetBytes.subarray(off,off+188);off+=188;if(p[1]&0x80)continue;let start=!!(p[1]&0x40),pid=((p[1]&31)<<8)|p[2],control=(p[3]>>4)&3;if(!(control&1))continue;let i=4;if(control&2){i+=1+p[i]}if(i>=188)continue;let payload=p.subarray(i);if(pid===0&&start){let found=parsePAT(payload);if(found>=0)pmtPid=found}else if(pid===pmtPid&&start)parsePMT(payload);else if(pid===videoPid){if(start)flushPES();pesParts.push(payload);pesLength+=payload.length}}packetBytes=packetBytes.slice(off)}
function draw(){if(rendering||!playing||!ctx)return;rendering=true;function step(){if(!playing){rendering=false;return}if(frames.length){let f=frames.shift();if(firstPts===null){firstPts=f.timestamp;clockStart=performance.now()}let due=clockStart+(f.timestamp-firstPts)/1000;if(performance.now()+3>=due){ctx.canvas.width=f.displayWidth;ctx.canvas.height=f.displayHeight;ctx.drawImage(f,0,0);f.close()}else frames.unshift(f)}setTimeout(step,8)}step()}
async function open(url){stopped=false;videoPid=-1;pmtPid=-1;packetBytes=new Uint8Array(0);pesParts=[];frames.forEach(f=>f.close());frames=[];firstPts=null;lastPts=0;decoder?.close();if(!('VideoDecoder' in self))throw Error('WebCodecs VideoDecoder unavailable');decoder=new VideoDecoder({output:f=>{frames.push(f);if(frames.length>40)frames.shift().close();draw()},error:e=>emit('error',{message:e.message})});decoder.configure({codec:'avc1.42E01E',optimizeForLatency:true});let r=await fetch(url);if(!r.ok||!r.body)throw Error('Stream HTTP '+r.status);emit('status',{text:'Receiving MPEG-TS stream'});let reader=r.body.getReader();while(!stopped){let {done,value}=await reader.read();if(done)break;parseTS(value)}flushPES();await decoder.flush();emit('status',{text:'Stream complete'});draw()}
self.onmessage=e=>{let m=e.data;try{if(m.type==='init'){ctx=m.canvas.getContext('2d');emit('status',{text:'Canvas initialized'})}if(m.type==='open')open(m.url).catch(err=>emit('error',{message:String(err)}));if(m.type==='pause'){playing=false;emit('playing',{value:false})}if(m.type==='resume'){playing=true;emit('playing',{value:true});draw()}if(m.type==='stop'){stopped=true;playing=false;frames.forEach(f=>f.close());frames=[]}if(m.type==='seek')emit('status',{text:'Seeking is a Phase 2 task; requested '+m.seconds+'s'})}catch(err){emit('error',{message:String(err)})}};
